<form
  class="txcm-dashboardListFilter"
  action="/filter">
    <input
      class="txcm-dashboardListFilterInput"
      type="search"
      placeholder="Поиск">
    <button
      class="txcm-dashboardListFilterCancel">
        Сбросить
    </button>
</form>
